### ISSUE TITLE
Twitter Card Meta Data

### ISSUE THREAD

**Issue by Samaxx** [s3bubble/Streamium-Netflix-Theme#67]
Social sharing data (Twitter Card) does not properly display for both series and videos with multiple episodes without the use of a 3rd party plugin.

**Comment by s3bubble** [comment]
Hi @Samaxx 

We have pushed this to our pre-release please feel free to test.

Go to customize and then Socal Cards add your Twitter handler and enable Twitter cards.

**Comment by Samaxx** [comment]
Hi,

I have enabled cards for videos and added my Twitter handle.

This is the error I am getting for all series and videos with multiple episodes. For a single Video it does not have an error but doesn’t load an image.

INFO:  Page fetched successfully
INFO:  5 metatags were found
ERROR: No card found (Card error)
WARN:  this card is redirected to https://sportversity.tv/shop/?r=1227

Thank you,
Sam

**Comment by s3bubble** [comment]
Hi @Samaxx 

Apologies we apply a few fixes please grab the latest tag.

https://github.com/s3bubble/Streamium-Netflix-Theme/releases/tag/v17.63

**Comment by Samaxx** [comment]
Hi,

We see the code on all videos now after  and it is correct, however I am still getting this error. I am not sure why this is still happening when I see the correct code?

INFO:  Page fetched successfully
INFO:  5 metatags were found
ERROR: No card found (Card error)
WARN:  this card is redirected to https://sportversity.tv/shop/?r=1330

**Comment by Samaxx** [comment]
I figured out why the cards are not working.

With the subscription and memberships plugin activated Twitter cannot access the thumbnail because it is redirected to the shop page.

How can we fix this?

Thank you,
Sam
